#ifndef CSGO_PARSING_BSPMAPLUMPS_H_
#define CSGO_PARSING_BSPMAPLUMPS_H_

// -------- start of source-sdk-2013 code --------
// Most of the information in here is taken from these 2 sources:
//   - source-sdk-2013/<...>/src/public/bspfile.h
//   - https://developer.valvesoftware.com/wiki/BSP_%28Source_1%29
// Some lumps might be wrongly named in regard to CSGO map files!

#define LUMP_IDX_ENTITIES                       ( 0)
#define LUMP_IDX_PLANES                         ( 1)
#define LUMP_IDX_TEXDATA                        ( 2)
#define LUMP_IDX_VERTEXES                       ( 3)
#define LUMP_IDX_VISIBILITY                     ( 4)
#define LUMP_IDX_NODES                          ( 5)
#define LUMP_IDX_TEXINFO                        ( 6)
#define LUMP_IDX_FACES                          ( 7)
#define LUMP_IDX_LIGHTING                       ( 8)
#define LUMP_IDX_OCCLUSION                      ( 9)
#define LUMP_IDX_LEAFS                          (10)
#define LUMP_IDX_FACEIDS                        (11)
#define LUMP_IDX_EDGES                          (12)
#define LUMP_IDX_SURFEDGES                      (13)
#define LUMP_IDX_MODELS                         (14)
#define LUMP_IDX_WORLDLIGHTS                    (15)
#define LUMP_IDX_LEAFFACES                      (16)
#define LUMP_IDX_LEAFBRUSHES                    (17)
#define LUMP_IDX_BRUSHES                        (18)
#define LUMP_IDX_BRUSHSIDES                     (19)
#define LUMP_IDX_AREAS                          (20)
#define LUMP_IDX_AREAPORTALS                    (21)
#define LUMP_IDX_PROPCOLLISION                  (22)
#define LUMP_IDX_PROPHULLS                      (23)
#define LUMP_IDX_PROPHULLVERTS                  (24)
#define LUMP_IDX_PROPTRIS                       (25)
#define LUMP_IDX_DISPINFO                       (26)
#define LUMP_IDX_ORIGINALFACES                  (27)
#define LUMP_IDX_PHYSDISP                       (28)
#define LUMP_IDX_PHYSCOLLIDE                    (29)
#define LUMP_IDX_VERTNORMALS                    (30)
#define LUMP_IDX_VERTNORMALINDICES              (31)
#define LUMP_IDX_DISP_LIGHTMAP_ALPHAS           (32)
#define LUMP_IDX_DISP_VERTS                     (33)
#define LUMP_IDX_DISP_LIGHTMAP_SAMPLE_POSITIONS (34)
#define LUMP_IDX_GAME_LUMP                      (35)
#define LUMP_IDX_LEAFWATERDATA                  (36)
#define LUMP_IDX_PRIMITIVES                     (37)
#define LUMP_IDX_PRIMVERTS                      (38)
#define LUMP_IDX_PRIMINDICES                    (39)
#define LUMP_IDX_PAKFILE                        (40)
#define LUMP_IDX_CLIPPORTALVERTS                (41)
#define LUMP_IDX_CUBEMAPS                       (42)
#define LUMP_IDX_TEXDATA_STRING_DATA            (43)
#define LUMP_IDX_TEXDATA_STRING_TABLE           (44)
#define LUMP_IDX_OVERLAYS                       (45)
#define LUMP_IDX_LEAFMINDISTTOWATER             (46)
#define LUMP_IDX_FACE_MACRO_TEXTURE_INFO        (47)
#define LUMP_IDX_DISP_TRIS                      (48)
#define LUMP_IDX_PROP_BLOB                      (49)
#define LUMP_IDX_WATEROVERLAYS                  (50)
#define LUMP_IDX_LEAF_AMBIENT_INDEX_HDR         (51)
#define LUMP_IDX_LEAF_AMBIENT_INDEX             (52)
#define LUMP_IDX_LIGHTING_HDR                   (53)
#define LUMP_IDX_WORLDLIGHTS_HDR                (54)
#define LUMP_IDX_LEAF_AMBIENT_LIGHTING_HDR      (55)
#define LUMP_IDX_LEAF_AMBIENT_LIGHTING          (56)
#define LUMP_IDX_XZIPPAKFILE                    (57)
#define LUMP_IDX_FACES_HDR                      (58)
#define LUMP_IDX_MAP_FLAGS                      (59)
#define LUMP_IDX_OVERLAY_FADES                  (60)
#define LUMP_IDX_OVERLAY_SYSTEM_LEVELS          (61)
#define LUMP_IDX_PHYSLEVEL                      (62)
#define LUMP_IDX_DISP_MULTIBLEND                (63)
// --------- end of source-sdk-2013 code ---------

#endif // CSGO_PARSING_BSPMAPLUMPS_H_
